from typing import Protocol

from movies.core.database import data_model


class IUserRepo(Protocol):
    async def get(self, email: str) -> data_model.User: ...
    async def create(self, display_name: str, email: str, password: str) -> None: ...
    async def authenticate(self, email: str, password: str) -> data_model.User: ...


class ISessionRepo(Protocol): ...


class IMovieRepo(Protocol):
    async def add(self, reference: str, title: str, image_url: str) -> None: ...
